import Head from "next/head";
import { Navbar, Hero, Testimonial, ProductOverview } from "@/components";

import Services from "@/components/Services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Hero />
        <ProductOverview />
        <Services />
        {/* <Testimonial /> */}
      </div>
    </>
  );
}
